version: '3.8'
services:
  web:
    image: "radar-evalution:1.0.0"
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - next:/usr/src/app/.next
volumes:
  node_modules:
  next: